services:
  - type: web
    name: rosettai
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: "streamlit run app/main.py --server.port=$PORT --server.address=0.0.0.0"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.13
      - key: GEMINI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
